// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRt6YolOOG8qNzBmUq0v70FxCeOF8_B2o',
    appId: '1:718003429762:web:745c57c837e29a58a0ef9b',
    messagingSenderId: '718003429762',
    projectId: 'specific-user-profile-auth',
    authDomain: 'specific-user-profile-auth.firebaseapp.com',
    storageBucket: 'specific-user-profile-auth.appspot.com',
    measurementId: 'G-TTQM5ZYVBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHLJ77T4qyPLBuOjVNPtIsiFbtocjdBjE',
    appId: '1:718003429762:android:2f813a7ab747d894a0ef9b',
    messagingSenderId: '718003429762',
    projectId: 'specific-user-profile-auth',
    storageBucket: 'specific-user-profile-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1aZ9LR4Uhlp4YPFVmJf8vflp2KMd1Y6I',
    appId: '1:718003429762:ios:1f77346a35913d24a0ef9b',
    messagingSenderId: '718003429762',
    projectId: 'specific-user-profile-auth',
    storageBucket: 'specific-user-profile-auth.appspot.com',
    iosBundleId: 'com.example.flutterProfileauth',
  );
}
